# Generated by Django 5.0.3 on 2024-03-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Charge",
            fields=[
                (
                    "apartment",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("january", models.DecimalField(decimal_places=2, max_digits=8)),
                ("february", models.DecimalField(decimal_places=2, max_digits=8)),
                ("march", models.DecimalField(decimal_places=2, max_digits=8)),
                ("april", models.DecimalField(decimal_places=2, max_digits=8)),
                ("may", models.DecimalField(decimal_places=2, max_digits=8)),
                ("june", models.DecimalField(decimal_places=2, max_digits=8)),
                ("july", models.DecimalField(decimal_places=2, max_digits=8)),
                ("august", models.DecimalField(decimal_places=2, max_digits=8)),
                ("september", models.DecimalField(decimal_places=2, max_digits=8)),
                ("october", models.DecimalField(decimal_places=2, max_digits=8)),
                ("november", models.DecimalField(decimal_places=2, max_digits=8)),
                ("december", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "apartment",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("january", models.DecimalField(decimal_places=2, max_digits=8)),
                ("february", models.DecimalField(decimal_places=2, max_digits=8)),
                ("march", models.DecimalField(decimal_places=2, max_digits=8)),
                ("april", models.DecimalField(decimal_places=2, max_digits=8)),
                ("may", models.DecimalField(decimal_places=2, max_digits=8)),
                ("june", models.DecimalField(decimal_places=2, max_digits=8)),
                ("july", models.DecimalField(decimal_places=2, max_digits=8)),
                ("august", models.DecimalField(decimal_places=2, max_digits=8)),
                ("september", models.DecimalField(decimal_places=2, max_digits=8)),
                ("october", models.DecimalField(decimal_places=2, max_digits=8)),
                ("november", models.DecimalField(decimal_places=2, max_digits=8)),
                ("december", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name="Saldo",
            fields=[
                (
                    "apartment",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("insaldo", models.DecimalField(decimal_places=2, max_digits=8)),
                ("outsaldo", models.DecimalField(decimal_places=2, max_digits=8)),
                ("january", models.DecimalField(decimal_places=2, max_digits=8)),
                ("february", models.DecimalField(decimal_places=2, max_digits=8)),
                ("march", models.DecimalField(decimal_places=2, max_digits=8)),
                ("april", models.DecimalField(decimal_places=2, max_digits=8)),
                ("may", models.DecimalField(decimal_places=2, max_digits=8)),
                ("june", models.DecimalField(decimal_places=2, max_digits=8)),
                ("july", models.DecimalField(decimal_places=2, max_digits=8)),
                ("august", models.DecimalField(decimal_places=2, max_digits=8)),
                ("september", models.DecimalField(decimal_places=2, max_digits=8)),
                ("october", models.DecimalField(decimal_places=2, max_digits=8)),
                ("november", models.DecimalField(decimal_places=2, max_digits=8)),
                ("december", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
